Repository liveview-native/liveview-client-swiftui, pull requests merged in 2024-09, with the labels that each got.

#1451 Update form with server state
  CHANGELOG.md
  Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift
  Sources/LiveViewNative/Live/LiveView.swift
  Sources/LiveViewNative/NavStackEntryView.swift
  Sources/LiveViewNative/Property Wrappers/FormState.swift
  Sources/LiveViewNative/ViewModel.swift
  Sources/LiveViewNative/Views/Controls and Indicators/Pickers/DatePicker.swift
  Sources/LiveViewNative/Views/Controls and Indicators/Pickers/Picker.swift
  Sources/LiveViewNative/Views/Controls and Indicators/Value Inputs/Slider.swift
  Sources/LiveViewNative/Views/Controls and Indicators/Value Inputs/Stepper.swift
  Sources/LiveViewNative/Views/Controls and Indicators/Value Inputs/Toggle.swift
  Sources/LiveViewNative/Views/Text Input and Output/SecureField.swift
  Sources/LiveViewNative/Views/Text Input and Output/TextEditor.swift
  Sources/LiveViewNative/Views/Text Input and Output/TextField.swift
Labels: v0.3

#1455 Fix retain cycle in LiveViewCoordinator
  CHANGELOG.md
  Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
  Sources/LiveViewNative/Coordinators/LiveViewCoordinator.swift
Labels: bug, v0.3

#1456 Allow to set optional headers
  CHANGELOG.md
  Sources/LiveViewNative/Coordinators/LiveSessionConfiguration.swift
  Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
Labels: v0.3, improvements

#1461 Turn `StylesheetCache` into a thread-safe actor
  CHANGELOG.md
  Sources/LiveViewNative/Coordinators/LiveSessionCoordinator.swift
  Sources/LiveViewNative/Stylesheets/Stylesheet.swift
Labels: v0.3, improvements
